name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  google_maps_flutter: ^0.5.30
  location: ^3.0.2
  flutter_blue: ^0.7.2
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  geolocator: ^6.2.1
  cloud_firestore: ^0.16.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
